//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Role { get; set; }
        public int MovieId { get; set; }
    
        public virtual Movie Movie { get; set; }
    }
}
